workflows:
  android-release:
    name: AI Robot PRO v2 - Android Release APK

    max_build_duration: 60

    environment:
      flutter: 3.47.2
      java: 17

    scripts:

      - name: Check Flutter Version
        script: |
          flutter --version
          dart --version

      - name: Clean Project
        script: |
          flutter clean
          rm -rf android/.gradle
          rm -rf ~/.gradle/caches
          rm -rf ~/.pub-cache

      - name: Get Packages
        script: |
          flutter pub get

      - name: Analyze Project
        script: |
          flutter analyze

      - name: Build Release APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
