workflows:
  android-release:

    name: AI Robot PRO v2 - Android Release APK

    max_build_duration: 60

    environment:
      flutter: 3.47.2
      java: 17

    scripts:

      - name: Check Environment
        script: |
          flutter --version
          dart --version
          java -version

      - name: Clean Flutter and Gradle
        script: |
          flutter clean
          rm -rf android/.gradle
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/wrapper
          rm -rf build

      - name: Get Packages
        script: |
          flutter pub get

      - name: Analyze
        script: |
          flutter analyze

      - name: Build Release APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
